src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @UniqueEntity(fields={"hour_start","room_id"}, message="Il existe déjà une réservation pour cette salle à cette horaire !")
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $bookingDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateStart;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $HourStart;


    /**
     * @ORM\Column(type="string")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=true)
     */
    private $room;


    /**
     * @var integer
     * @ORM\Column(type="integer",name="duration")
     */
    private $duration;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="booking")
     * @ORM\JoinColumn(nullable=true)
     */
    private $user;

    public function __construct()
    {
        $this->bookingDate = new \DateTime();
        $this->bookingDate->setTime(00, 00, 00);
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBookingDate(): ?\DateTime
    {
        return $this->bookingDate;
    }

    public function setBookingDate(\DateTime $bookingDate): self
    {
        $this->bookingDate = $bookingDate;

        return $this;
    }

    public function getDateStart(): ?\DateTime
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTime $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getHourStart(): ?\DateTimeInterface
    {
        return $this->HourStart;
    }

    public function setHourStart(\DateTimeInterface $HourStart): self
    {
        $this->HourStart = $HourStart;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return int
     */
    public function getDuration(): int
    {
        return $this->duration;
    }

    /**
     * @param int $duration
     */
    public function setDuration(int $duration): void
    {
        $this->duration = $duration;
    }




}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"},message="Il existe déjà un utilisateur avec cet email !")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @var array
     *
     * @ORM\Column(name="roles", type="array", nullable=false)
     */
    private $roles = [];

    /**
     * @var string
     * @Assert\NotBlank(message="Le mot de pass est obligatoire !")
     * @Assert\Length(min="6",minMessage="Le mot de passe doit faire au moins {{ limit }} caractères")
     */
    private $plainPassword;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="user")
     */
    private $booking;


    public function __construct()
    {
        $this->booking = new ArrayCollection();
        $this->roles[]=  'ROLE_USER';
    }

    public function __toString()
    {
        return $this->firstname. ' '.$this->lastname;
    }


    /**
     * @return string
     */
    public function getPlainPassword():? string
    {
        return $this->plainPassword;
    }

    /**
     * @param string $plainPassword
     * @return User
     */
    public function setPlainPassword(string $plainPassword): User
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }


    /**
     * @return array
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    /**
     * @param array $roles
     * @return User
     */
    public function setRoles(array $roles): User
    {
        $this->roles = $roles;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

   


    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {

    }

    /**
     * @return Collection|Booking[]
     */
    public function getBooking(): Collection
    {
        return $this->booking;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->booking->contains($booking)) {
            $this->booking[] = $booking;
            $booking->setUser($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->booking->contains($booking)) {
            $this->booking->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getUser() === $this) {
                $booking->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('lastname',TextType::class,[
                'label'=> 'Nom'
            ])
            ->add('firstname',TextType::class,[
                'label' => 'Prénom'
            ])
            ->add('email',EmailType::class,[
                'label' =>'Email'
            ])
            ->add('plainPassword',RepeatedType::class,
                [
                    'type' => PasswordType::class,
                    'first_options' => [
                        'label' => 'Mot de passe'
                    ],
                    'second_options' =>[
                        'label' => 'Répéter le mot de passe'
                    ],
                    'invalid_message' => 'les mots de passe ne sont pas identiques !'
                ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'csrf_protection'   => false
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;


use App\Entity\Booking;
use App\Entity\User;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\HttpFoundation\Response;

class UserController extends AbstractController
{
    /**
     * @Route("/user", name="user")
     */
    public function index()
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

    /**
     * @Route("/login", name="login")
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     */
    public function login(AuthenticationUtils $authenticationUtils)
    {

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();


        return $this->render('user/login.html.twig',[

            'last_username' => $lastUsername,
            'error' => $error
        ]);
    }

    /**
     * @Route("/deconnexion" ,name="logout")
     */
    public function logout(){}


    /**
     * @param User $user
     * @param $deleted
     * @return Response
     * @Route("/userBooking/{id}/{deleted}", defaults={"deleted" : null}, name="user_booking")
     */
    public function userBooking(User $user, $deleted)
    {
       #FIXME deleted value from booking is null ??

        if (!empty($deleted) and $deleted == true)
        {

            $this->addFlash('success', "La réservation est supprimée");
        }
        if (!empty($deleted) and $deleted == false)
        {
            $this->addFlash('success', "La réservation est enregistrée");
        }

        $liste = $user->getBooking();



        return $this->render(
            'user/user_booking.html.twig',
            [
                'liste' => $liste,
                'user_booking' => $user

            ]
        );
    }

    /**
     * @param ObjectManager $manager
     * @param Booking $booking
     * @param $admin
     * @return RedirectResponse
     * @Route("/deleteUserBooking/{id}/{admin}",defaults={"admin" : null },requirements={"admin" : "\d+" }, name="delete_user_booking")
     */
    public function deleteUserBooking(ObjectManager $manager, Booking $booking,$admin)
    {
        $user = $this->getUser();


        $manager->remove($booking);
        $manager->flush();

        $deleted = true;

        // If delete user booking come from admin
        if (!null == $admin) {
            $lastNameUser = $booking->getUser()->getLastname();
            $firstNameUser = $booking->getUser()->getFirstname();
            $this->addFlash('success',"La réservation de $firstNameUser $lastNameUser à bien été supprimée");
            return $this->redirectToRoute('admin_edit_user',[

            ]);
        }

        return $this->redirectToRoute('user_booking', [
            'id'=> $user->getId(),
            'deleted' =>$deleted

        ]);

    }

}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/sebvr/Desktop/Projets/EasyBoardRoom/easyboardroom/src/Controller/UserController.php'|file_link(0) }}">src/Controller/UserController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/sebvr/Desktop/Projets/EasyBoardRoom/easyboardroom/templates/user/index.html.twig'|file_link(0) }}">templates/user/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/user/login.html.twig
{% extends 'layout2.html.twig' %}
{% block title %}{% endblock %}
{% block stylesheets %}{{ parent() }} {% endblock %}
{% block body %}
{{ parent() }}
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading text-uppercase">Se connecter</h2>
                    <br>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                     <div class="post-preview">


                            <div class="card text-center">
                                <form method="post">

                                    <div class="card-header">Connectez-vous<br>

                                        {% for type, messages in app.session.flashBag.all %}
                                            {% for message in messages %}
                                                {% if type == 'error' %}
                                                    {% set type = 'danger' %}
                                                {% endif %}
                                                <div class="alert alert-{{ type }} mt-2">
                                                    {{ message|raw }}
                                                </div>
                                            {% endfor %}
                                        {% endfor %}

                                    </div>
                                    <div class="card-body">
                                        <div class="row">

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label >Email</label>
                                                    <input type="text" name="_username" class="form-control" value="{{ last_username }}">
                                                </div>

                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label >Mot de passe</label>
                                                    <input type="password" name="_password" class="form-control">
                                                </div>
                                            </div>

                                        </div>


                                    </div>
                                    <div class="clearfix"></div>


                                    <div class="col-lg-12 text-center">
                                        <div class="card-footer">
                                            <div id="success"></div>
                                            <button id="sendMessageButton" class="btn btn-outline-dark btn-xl text-uppercase" type="submit"> Connexion</button>
                                        </div>
                                    </div>

                                </form>
                            </div>
                     </div>


                </div>
            </div>
        </div>
    <hr>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p class="copyright text-muted">Copyright &copy; EasyBoardRoom 2019</p>

            </div>
        </div>
    </div>
</footer>
{% endblock %}

{% block javascripts %}
{{ parent() }}
{% endblock %}

templates/user/user_booking.html.twig
{% extends 'layout2.html.twig' %}

{% block title %}Vos réservations{% endblock %}
{% block stylesheets %}{{ parent() }} {% endblock %}

{% block body %}
    {{ parent() }}




    {% if liste|length == 0  %}
        <h3><p class="text-center">Aucune réservation</p></h3>
    {% else %}
        <h3 class="text-center">Réservations de <strong>{{ user_booking.firstname }} {{ user_booking.lastname }}</strong></h3>
   <table class="table table-striped">
       <thead class="thead-light">
            <tr>
                <th scope="col">Salle</th>
                <th scope="col">Réservation effectuée le:</th>
                <th scope="col">Date de la réservation</th>
                <th scope="col">Heure de début de la réservation</th>
                <th scope="col">Durée de la réservation</th>
                <th scope="col">Supression</th>
            </tr>
       </thead>
       <tbody>
        {% for booking in liste %}
            <tr>
                <td>{{ booking.room.name }}</td>
                <td>{{ booking.bookingDate | date('d-m-Y') }}</td>
                <td>{{ booking.dateStart | date('d-m-Y') }}</td>
                <td>{{ booking.hourStart | date('H:i') }}</td>
                <td>{{ booking.duration }} h</td>
                <td>
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('delete_user_booking', {'id': booking.id, 'admin' : 1}) }}"
                           class="btn btn-danger">
                            Supprimer
                        </a>
                    {% else %}
                    <a href="{{ path('delete_user_booking', {'id': booking.id}) }}"
                       class="btn btn-danger">
                        Supprimer
                    </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
       </tbody>
    </table>
    {% endif %}
    <div class="text-right mb-3">
        {% if is_granted('ROLE_ADMIN') %}
         <a href="{{ path('admin_edit_user') }}" class="btn btn-outline-secondary">Retour</a>
        {% else %}
            <a href="{{ path('home') }}"
               class="btn btn-outline-secondary">
                Retour
            </a>
        {% endif %}
    </div>
{% endblock %}